--Script pra criar o Schema do projeto com as tabelas
--CREATE NECESSÁRIO APENAS NA NÃO EXISTÊNCIA DO SCHEMA FINANCEIRO:
--CREATE USER FINANCEIRO IDENTIFIED BY oracle;

/*GRANT CONNECT TO FINANCEIRO;
GRANT CONNECT, RESOURCE, DBA TO FINANCEIRO;
GRANT CREATE SESSION TO FINANCEIRO;
GRANT DBA TO FINANCEIRO;
GRANT CREATE VIEW, CREATE PROCEDURE, CREATE SEQUENCE to FINANCEIRO;
GRANT UNLIMITED TABLESPACE TO FINANCEIRO;
GRANT CREATE MATERIALIZED VIEW TO FINANCEIRO;
GRANT CREATE TABLE TO FINANCEIRO;
GRANT GLOBAL QUERY REWRITE TO FINANCEIRO;
GRANT SELECT ANY TABLE TO FINANCEIRO;*/

CREATE TABLE "Item" (
	"id_item" NUMBER NOT NULL,
	"nome" VARCHAR2(50) NOT NULL,
	"valor" NUMBER(10, 4) NOT NULL,
	PRIMARY KEY ("id_item")
);

CREATE TABLE "Cliente" (
	"id_cliente" NUMBER NOT NULL,
	"cpf_cliente" CHAR(11) UNIQUE NOT NULL,
	"nome" VARCHAR2(255) NOT NULL,
	PRIMARY KEY ("id_cliente")
);

CREATE TABLE "Conta" (
	"numero_conta" NUMBER(6) NOT NULL,
	"id_cliente" NUMBER NOT NULL,
	"senha" VARCHAR2(20) NOT NULL,
	"agencia" NUMBER(4) NOT NULL,
	"saldo" NUMBER(10, 4) NOT NULL,
	"cheque_especial" NUMBER(10, 4) NOT NULL,
	PRIMARY KEY ("numero_conta"),
	CONSTRAINT "FK_Conta.id_cliente" FOREIGN KEY ("id_cliente") REFERENCES "Cliente"("id_cliente")
);

CREATE TABLE "Cartao" (
	"id_cartao" NUMBER NOT NULL,
	"numero_conta" NUMBER(6) NOT NULL,
	"numero_cartao" NUMBER(16) UNIQUE NOT NULL,
	"data_expedicao" DATE NOT NULL,
	"codigo_seguranca" NUMBER(3) NOT NULL,
	"tipo" NUMBER(1) NOT NULL,
	"vencimento" DATE NOT NULL,
	PRIMARY KEY ("id_cartao"),
	CONSTRAINT "FK_Cartao.numero_conta" FOREIGN KEY ("numero_conta") REFERENCES "Conta"("numero_conta")
);

CREATE TABLE "Compra" (
	"id_compra" NUMBER NOT NULL,
	"id_cartao" NUMBER NOT NULL,
	"doc_vendedor" VARCHAR2(12) NOT NULL,
	"data" DATE NOT NULL,
	PRIMARY KEY ("id_compra"),
	CONSTRAINT "FK_Compra.id_cartao" FOREIGN KEY ("id_cartao") REFERENCES "Cartao"("id_cartao")
);

CREATE TABLE "CompraItem" (
	"id_compra" NUMBER NOT NULL,
	"id_item" NUMBER NOT NULL,
	"quantidade" NUMBER NOT NULL,
	PRIMARY KEY ("id_compra", "id_item"),
	CONSTRAINT "FK_CompraItem.id_item" FOREIGN KEY ("id_item") REFERENCES "Item"("id_item"),
	CONSTRAINT "FK_CompraItem.id_compra" FOREIGN KEY ("id_compra") REFERENCES "Compra"("id_compra")
);

CREATE TABLE "Endereco" (
	"id_endereco" NUMBER NOT NULL,
	"id_cliente" NUMBER NOT NULL,
	"cidade" VARCHAR2(255) NOT NULL,
	"logradouro" VARCHAR2(255) NOT NULL,
	"estado" VARCHAR2(255) NOT NULL,
	"pais" VARCHAR2(255) NOT NULL,
	"cep" VARCHAR2(255) NOT NULL,
	PRIMARY KEY ("id_endereco"),
	CONSTRAINT "FK_Endereco.id_cliente" FOREIGN KEY ("id_cliente") REFERENCES "Cliente"("id_cliente")
);

CREATE TABLE "Transferencia" (
	"id_transferencia" NUMBER NOT NULL,
	"numero_conta_enviou" NUMBER NOT NULL,
	"numero_conta_recebeu" NUMBER NOT NULL,
	"valor" NUMBER(10, 4) NOT NULL,
	PRIMARY KEY ("id_transferencia"),
	CONSTRAINT "FK_Transferencia_recebeu" FOREIGN KEY ("numero_conta_recebeu") REFERENCES "Conta"("numero_conta"),
	CONSTRAINT "FK_Transferencia_enviou" FOREIGN KEY ("numero_conta_enviou") REFERENCES "Conta"("numero_conta")
);

CREATE TABLE "Contato" (
	"id_contato" NUMBER NOT NULL,
	"id_cliente" NUMBER NOT NULL,
	"telefone" VARCHAR2(20) NOT NULL,
	"email " VARCHAR2(100) NOT NULL,
	PRIMARY KEY ("id_contato"),
	CONSTRAINT "FK_Contato.id_cliente" FOREIGN KEY ("id_cliente") REFERENCES "Cliente"("id_cliente")
);

CREATE SEQUENCE SEQ_CLIENTE
START WITH 1
INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_ENDERECO
START WITH 1
INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_CONTATO
START WITH 1
INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_CARTAO
START WITH 1
INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_COMPRA
START WITH 1
INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_ITEM
START WITH 1
INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_COMPRA_ITEM
START WITH 1
INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_TRANSFERENCIA
START WITH 1
INCREMENT BY 1 NOCACHE NOCYCLE;